export interface SeedAsset {
  id: string;
  category: "fiat" | "crypto" | "stock" | "etf";
  name: string;
  symbol: string;
  enabled?: boolean;
}

export const SEED_ASSETS: SeedAsset[] = [
  // === FIAT (8) ===
  { id: "USD", category: "fiat", name: "US Dollar", symbol: "USD", enabled: true },
  { id: "EUR", category: "fiat", name: "Euro", symbol: "EUR", enabled: true },
  { id: "UAH", category: "fiat", name: "Ukrainian Hryvnia", symbol: "UAH", enabled: true },
  { id: "GBP", category: "fiat", name: "British Pound", symbol: "GBP" },
  { id: "CHF", category: "fiat", name: "Swiss Franc", symbol: "CHF" },
  { id: "JPY", category: "fiat", name: "Japanese Yen", symbol: "JPY" },
  { id: "CAD", category: "fiat", name: "Canadian Dollar", symbol: "CAD" },
  { id: "PLN", category: "fiat", name: "Polish Zloty", symbol: "PLN" },

  // === CRYPTO (100) ===
  { id: "bitcoin", category: "crypto", name: "Bitcoin", symbol: "BTC", enabled: true },
  { id: "ethereum", category: "crypto", name: "Ethereum", symbol: "ETH", enabled: true },
  { id: "tether", category: "crypto", name: "Tether", symbol: "USDT", enabled: true },
  { id: "ripple", category: "crypto", name: "XRP", symbol: "XRP", enabled: true },
  { id: "binancecoin", category: "crypto", name: "BNB", symbol: "BNB" },
  { id: "solana", category: "crypto", name: "Solana", symbol: "SOL", enabled: true },
  { id: "usd-coin", category: "crypto", name: "USD Coin", symbol: "USDC" },
  { id: "dogecoin", category: "crypto", name: "Dogecoin", symbol: "DOGE" },
  { id: "cardano", category: "crypto", name: "Cardano", symbol: "ADA" },
  { id: "tron", category: "crypto", name: "TRON", symbol: "TRX" },
  { id: "avalanche-2", category: "crypto", name: "Avalanche", symbol: "AVAX" },
  { id: "chainlink", category: "crypto", name: "Chainlink", symbol: "LINK" },
  { id: "shiba-inu", category: "crypto", name: "Shiba Inu", symbol: "SHIB" },
  { id: "stellar", category: "crypto", name: "Stellar", symbol: "XLM" },
  { id: "sui", category: "crypto", name: "Sui", symbol: "SUI" },
  { id: "hedera-hashgraph", category: "crypto", name: "Hedera", symbol: "HBAR" },
  { id: "bitcoin-cash", category: "crypto", name: "Bitcoin Cash", symbol: "BCH" },
  { id: "polkadot", category: "crypto", name: "Polkadot", symbol: "DOT" },
  { id: "litecoin", category: "crypto", name: "Litecoin", symbol: "LTC" },
  { id: "hyperliquid", category: "crypto", name: "Hyperliquid", symbol: "HYPE" },
  { id: "uniswap", category: "crypto", name: "Uniswap", symbol: "UNI" },
  { id: "dai", category: "crypto", name: "Dai", symbol: "DAI" },
  { id: "leo-token", category: "crypto", name: "LEO Token", symbol: "LEO" },
  { id: "near", category: "crypto", name: "NEAR Protocol", symbol: "NEAR" },
  { id: "ethereum-classic", category: "crypto", name: "Ethereum Classic", symbol: "ETC" },
  { id: "aptos", category: "crypto", name: "Aptos", symbol: "APT" },
  { id: "internet-computer", category: "crypto", name: "Internet Computer", symbol: "ICP" },
  { id: "pepe", category: "crypto", name: "Pepe", symbol: "PEPE" },
  { id: "aave", category: "crypto", name: "Aave", symbol: "AAVE" },
  { id: "render-token", category: "crypto", name: "Render", symbol: "RENDER" },
  { id: "mantle", category: "crypto", name: "Mantle", symbol: "MNT" },
  { id: "cronos", category: "crypto", name: "Cronos", symbol: "CRO" },
  { id: "vechain", category: "crypto", name: "VeChain", symbol: "VET" },
  { id: "cosmos", category: "crypto", name: "Cosmos Hub", symbol: "ATOM" },
  { id: "filecoin", category: "crypto", name: "Filecoin", symbol: "FIL" },
  { id: "kaspa", category: "crypto", name: "Kaspa", symbol: "KAS" },
  { id: "algorand", category: "crypto", name: "Algorand", symbol: "ALGO" },
  { id: "arbitrum", category: "crypto", name: "Arbitrum", symbol: "ARB" },
  { id: "optimism", category: "crypto", name: "Optimism", symbol: "OP" },
  { id: "fantom", category: "crypto", name: "Fantom", symbol: "FTM" },
  { id: "theta-token", category: "crypto", name: "Theta Network", symbol: "THETA" },
  { id: "the-graph", category: "crypto", name: "The Graph", symbol: "GRT" },
  { id: "injective-protocol", category: "crypto", name: "Injective", symbol: "INJ" },
  { id: "immutable-x", category: "crypto", name: "Immutable", symbol: "IMX" },
  { id: "ondo-finance", category: "crypto", name: "Ondo", symbol: "ONDO" },
  { id: "stacks", category: "crypto", name: "Stacks", symbol: "STX" },
  { id: "mantra", category: "crypto", name: "MANTRA", symbol: "OM" },
  { id: "maker", category: "crypto", name: "Maker", symbol: "MKR" },
  { id: "celestia", category: "crypto", name: "Celestia", symbol: "TIA" },
  { id: "flow", category: "crypto", name: "Flow", symbol: "FLOW" },
  { id: "the-sandbox", category: "crypto", name: "The Sandbox", symbol: "SAND" },
  { id: "axie-infinity", category: "crypto", name: "Axie Infinity", symbol: "AXS" },
  { id: "decentraland", category: "crypto", name: "Decentraland", symbol: "MANA" },
  { id: "gala", category: "crypto", name: "Gala", symbol: "GALA" },
  { id: "eos", category: "crypto", name: "EOS", symbol: "EOS" },
  { id: "neo", category: "crypto", name: "Neo", symbol: "NEO" },
  { id: "iota", category: "crypto", name: "IOTA", symbol: "IOTA" },
  { id: "kucoin-shares", category: "crypto", name: "KuCoin Token", symbol: "KCS" },
  { id: "quant-network", category: "crypto", name: "Quant", symbol: "QNT" },
  { id: "astar", category: "crypto", name: "Astar", symbol: "ASTR" },
  { id: "chiliz", category: "crypto", name: "Chiliz", symbol: "CHZ" },
  { id: "nexo", category: "crypto", name: "Nexo", symbol: "NEXO" },
  { id: "curve-dao-token", category: "crypto", name: "Curve DAO Token", symbol: "CRV" },
  { id: "ecash", category: "crypto", name: "eCash", symbol: "XEC" },
  { id: "arweave", category: "crypto", name: "Arweave", symbol: "AR" },
  { id: "floki", category: "crypto", name: "FLOKI", symbol: "FLOKI" },
  { id: "raydium", category: "crypto", name: "Raydium", symbol: "RAY" },
  { id: "tezos", category: "crypto", name: "Tezos", symbol: "XTZ" },
  { id: "bitcoin-sv", category: "crypto", name: "Bitcoin SV", symbol: "BSV" },
  { id: "monero", category: "crypto", name: "Monero", symbol: "XMR" },
  { id: "okb", category: "crypto", name: "OKB", symbol: "OKB" },
  { id: "gatetoken", category: "crypto", name: "Gate", symbol: "GT" },
  { id: "thorchain", category: "crypto", name: "THORChain", symbol: "RUNE" },
  { id: "fetch-ai", category: "crypto", name: "Artificial Superintelligence Alliance", symbol: "FET" },
  { id: "zcash", category: "crypto", name: "Zcash", symbol: "ZEC" },
  { id: "lido-dao", category: "crypto", name: "Lido DAO", symbol: "LDO" },
  { id: "sei-network", category: "crypto", name: "Sei", symbol: "SEI" },
  { id: "worldcoin-wld", category: "crypto", name: "Worldcoin", symbol: "WLD" },
  { id: "bonk", category: "crypto", name: "Bonk", symbol: "BONK" },
  { id: "jupiter-exchange-solana", category: "crypto", name: "Jupiter", symbol: "JUP" },
  { id: "pyth-network", category: "crypto", name: "Pyth Network", symbol: "PYTH" },
  { id: "jito-governance-token", category: "crypto", name: "Jito", symbol: "JTO" },
  { id: "ethena", category: "crypto", name: "Ethena", symbol: "ENA" },
  { id: "pendle", category: "crypto", name: "Pendle", symbol: "PENDLE" },
  { id: "wormhole", category: "crypto", name: "Wormhole", symbol: "W" },
  { id: "dydx-chain", category: "crypto", name: "dYdX", symbol: "DYDX" },
  { id: "beam-2", category: "crypto", name: "Beam", symbol: "BEAM" },
  { id: "blur", category: "crypto", name: "Blur", symbol: "BLUR" },
  { id: "mina-protocol", category: "crypto", name: "Mina Protocol", symbol: "MINA" },
  { id: "synthetix-network-token", category: "crypto", name: "Synthetix", symbol: "SNX" },
  { id: "compound-governance-token", category: "crypto", name: "Compound", symbol: "COMP" },
  { id: "1inch", category: "crypto", name: "1inch", symbol: "1INCH" },
  { id: "pancakeswap-token", category: "crypto", name: "PancakeSwap", symbol: "CAKE" },
  { id: "rocket-pool", category: "crypto", name: "Rocket Pool", symbol: "RPL" },
  { id: "gmx", category: "crypto", name: "GMX", symbol: "GMX" },
  { id: "sushiswap", category: "crypto", name: "SushiSwap", symbol: "SUSHI" },
  { id: "convex-finance", category: "crypto", name: "Convex Finance", symbol: "CVX" },
  { id: "yearn-finance", category: "crypto", name: "yearn.finance", symbol: "YFI" },
  { id: "loopring", category: "crypto", name: "Loopring", symbol: "LRC" },
  { id: "enjincoin", category: "crypto", name: "Enjin Coin", symbol: "ENJ" },

  // === STOCKS (100) ===
  { id: "AAPL", category: "stock", name: "Apple Inc.", symbol: "AAPL", enabled: true },
  { id: "MSFT", category: "stock", name: "Microsoft Corporation", symbol: "MSFT", enabled: true },
  { id: "NVDA", category: "stock", name: "NVIDIA Corporation", symbol: "NVDA", enabled: true },
  { id: "AMZN", category: "stock", name: "Amazon.com, Inc.", symbol: "AMZN", enabled: true },
  { id: "GOOGL", category: "stock", name: "Alphabet Inc.", symbol: "GOOGL", enabled: true },
  { id: "META", category: "stock", name: "Meta Platforms, Inc.", symbol: "META", enabled: true },
  { id: "BRK-B", category: "stock", name: "Berkshire Hathaway Inc.", symbol: "BRK-B" },
  { id: "LLY", category: "stock", name: "Eli Lilly and Company", symbol: "LLY" },
  { id: "TSM", category: "stock", name: "Taiwan Semiconductor Manufacturing Company", symbol: "TSM" },
  { id: "AVGO", category: "stock", name: "Broadcom Inc.", symbol: "AVGO" },
  { id: "JPM", category: "stock", name: "JPMorgan Chase & Co.", symbol: "JPM" },
  { id: "WMT", category: "stock", name: "Walmart Inc.", symbol: "WMT" },
  { id: "V", category: "stock", name: "Visa Inc.", symbol: "V" },
  { id: "UNH", category: "stock", name: "UnitedHealth Group Incorporated", symbol: "UNH" },
  { id: "MA", category: "stock", name: "Mastercard Incorporated", symbol: "MA" },
  { id: "XOM", category: "stock", name: "Exxon Mobil Corporation", symbol: "XOM" },
  { id: "COST", category: "stock", name: "Costco Wholesale Corporation", symbol: "COST" },
  { id: "ORCL", category: "stock", name: "Oracle Corporation", symbol: "ORCL" },
  { id: "HD", category: "stock", name: "The Home Depot, Inc.", symbol: "HD" },
  { id: "PG", category: "stock", name: "The Procter & Gamble Company", symbol: "PG" },
  { id: "NFLX", category: "stock", name: "Netflix, Inc.", symbol: "NFLX" },
  { id: "JNJ", category: "stock", name: "Johnson & Johnson", symbol: "JNJ" },
  { id: "BAC", category: "stock", name: "Bank of America Corporation", symbol: "BAC" },
  { id: "CRM", category: "stock", name: "Salesforce, Inc.", symbol: "CRM" },
  { id: "ABBV", category: "stock", name: "AbbVie Inc.", symbol: "ABBV" },
  { id: "CVX", category: "stock", name: "Chevron Corporation", symbol: "CVX" },
  { id: "TMUS", category: "stock", name: "T-Mobile US, Inc.", symbol: "TMUS" },
  { id: "KO", category: "stock", name: "The Coca-Cola Company", symbol: "KO" },
  { id: "MRK", category: "stock", name: "Merck & Co., Inc.", symbol: "MRK" },
  { id: "AMD", category: "stock", name: "Advanced Micro Devices, Inc.", symbol: "AMD" },
  { id: "WFC", category: "stock", name: "Wells Fargo & Company", symbol: "WFC" },
  { id: "CSCO", category: "stock", name: "Cisco Systems, Inc.", symbol: "CSCO" },
  { id: "NOW", category: "stock", name: "ServiceNow, Inc.", symbol: "NOW" },
  { id: "ACN", category: "stock", name: "Accenture plc", symbol: "ACN" },
  { id: "LIN", category: "stock", name: "Linde plc", symbol: "LIN" },
  { id: "MCD", category: "stock", name: "McDonald's Corporation", symbol: "MCD" },
  { id: "IBM", category: "stock", name: "International Business Machines Corporation", symbol: "IBM" },
  { id: "ABT", category: "stock", name: "Abbott Laboratories", symbol: "ABT" },
  { id: "PM", category: "stock", name: "Philip Morris International Inc.", symbol: "PM" },
  { id: "GE", category: "stock", name: "GE Aerospace", symbol: "GE" },
  { id: "CAT", category: "stock", name: "Caterpillar Inc.", symbol: "CAT" },
  { id: "ISRG", category: "stock", name: "Intuitive Surgical, Inc.", symbol: "ISRG" },
  { id: "DIS", category: "stock", name: "The Walt Disney Company", symbol: "DIS" },
  { id: "INTU", category: "stock", name: "Intuit Inc.", symbol: "INTU" },
  { id: "VZ", category: "stock", name: "Verizon Communications Inc.", symbol: "VZ" },
  { id: "AMGN", category: "stock", name: "Amgen Inc.", symbol: "AMGN" },
  { id: "QCOM", category: "stock", name: "QUALCOMM Incorporated", symbol: "QCOM" },
  { id: "TXN", category: "stock", name: "Texas Instruments Incorporated", symbol: "TXN" },
  { id: "GS", category: "stock", name: "The Goldman Sachs Group, Inc.", symbol: "GS" },
  { id: "PFE", category: "stock", name: "Pfizer Inc.", symbol: "PFE" },
  { id: "BLK", category: "stock", name: "BlackRock, Inc.", symbol: "BLK" },
  { id: "MS", category: "stock", name: "Morgan Stanley", symbol: "MS" },
  { id: "AXP", category: "stock", name: "American Express Company", symbol: "AXP" },
  { id: "RTX", category: "stock", name: "RTX Corporation", symbol: "RTX" },
  { id: "T", category: "stock", name: "AT&T Inc.", symbol: "T" },
  { id: "BKNG", category: "stock", name: "Booking Holdings Inc.", symbol: "BKNG" },
  { id: "LOW", category: "stock", name: "Lowe's Companies, Inc.", symbol: "LOW" },
  { id: "SPGI", category: "stock", name: "S&P Global Inc.", symbol: "SPGI" },
  { id: "NEE", category: "stock", name: "NextEra Energy, Inc.", symbol: "NEE" },
  { id: "SCHW", category: "stock", name: "The Charles Schwab Corporation", symbol: "SCHW" },
  { id: "DHR", category: "stock", name: "Danaher Corporation", symbol: "DHR" },
  { id: "HON", category: "stock", name: "Honeywell International Inc.", symbol: "HON" },
  { id: "UNP", category: "stock", name: "Union Pacific Corporation", symbol: "UNP" },
  { id: "SYK", category: "stock", name: "Stryker Corporation", symbol: "SYK" },
  { id: "C", category: "stock", name: "Citigroup Inc.", symbol: "C" },
  { id: "PLD", category: "stock", name: "Prologis, Inc.", symbol: "PLD" },
  { id: "AMAT", category: "stock", name: "Applied Materials, Inc.", symbol: "AMAT" },
  { id: "VRTX", category: "stock", name: "Vertex Pharmaceuticals Incorporated", symbol: "VRTX" },
  { id: "DE", category: "stock", name: "Deere & Company", symbol: "DE" },
  { id: "MDT", category: "stock", name: "Medtronic plc", symbol: "MDT" },
  { id: "BSX", category: "stock", name: "Boston Scientific Corporation", symbol: "BSX" },
  { id: "LRCX", category: "stock", name: "Lam Research Corporation", symbol: "LRCX" },
  { id: "CB", category: "stock", name: "Chubb Limited", symbol: "CB" },
  { id: "ADI", category: "stock", name: "Analog Devices, Inc.", symbol: "ADI" },
  { id: "PANW", category: "stock", name: "Palo Alto Networks, Inc.", symbol: "PANW" },
  { id: "BMY", category: "stock", name: "Bristol-Myers Squibb Company", symbol: "BMY" },
  { id: "KLAC", category: "stock", name: "KLA Corporation", symbol: "KLAC" },
  { id: "GILD", category: "stock", name: "Gilead Sciences, Inc.", symbol: "GILD" },
  { id: "CI", category: "stock", name: "The Cigna Group", symbol: "CI" },
  { id: "ADP", category: "stock", name: "Automatic Data Processing, Inc.", symbol: "ADP" },
  { id: "FI", category: "stock", name: "Fiserv, Inc.", symbol: "FI" },
  { id: "MO", category: "stock", name: "Altria Group, Inc.", symbol: "MO" },
  { id: "SO", category: "stock", name: "The Southern Company", symbol: "SO" },
  { id: "MDLZ", category: "stock", name: "Mondelez International, Inc.", symbol: "MDLZ" },
  { id: "CME", category: "stock", name: "CME Group Inc.", symbol: "CME" },
  { id: "REGN", category: "stock", name: "Regeneron Pharmaceuticals, Inc.", symbol: "REGN" },
  { id: "SHW", category: "stock", name: "The Sherwin-Williams Company", symbol: "SHW" },
  { id: "SNPS", category: "stock", name: "Synopsys, Inc.", symbol: "SNPS" },
  { id: "CDNS", category: "stock", name: "Cadence Design Systems, Inc.", symbol: "CDNS" },
  { id: "PGR", category: "stock", name: "The Progressive Corporation", symbol: "PGR" },
  { id: "ICE", category: "stock", name: "Intercontinental Exchange, Inc.", symbol: "ICE" },
  { id: "ITW", category: "stock", name: "Illinois Tool Works Inc.", symbol: "ITW" },
  { id: "EOG", category: "stock", name: "EOG Resources, Inc.", symbol: "EOG" },
  { id: "APD", category: "stock", name: "Air Products and Chemicals, Inc.", symbol: "APD" },
  { id: "USB", category: "stock", name: "U.S. Bancorp", symbol: "USB" },
  { id: "ZTS", category: "stock", name: "Zoetis Inc.", symbol: "ZTS" },
  { id: "TJX", category: "stock", name: "The TJX Companies, Inc.", symbol: "TJX" },
  { id: "MMC", category: "stock", name: "Marsh & McLennan Companies, Inc.", symbol: "MMC" },
  { id: "MCK", category: "stock", name: "McKesson Corporation", symbol: "MCK" },
  { id: "ADBE", category: "stock", name: "Adobe Inc.", symbol: "ADBE" },

  // === ETFs (100) ===
  { id: "SPY", category: "etf", name: "SPDR S&P 500 ETF Trust", symbol: "SPY", enabled: true },
  { id: "IVV", category: "etf", name: "iShares Core S&P 500 ETF", symbol: "IVV", enabled: true },
  { id: "VOO", category: "etf", name: "Vanguard S&P 500 ETF", symbol: "VOO", enabled: true },
  { id: "VTI", category: "etf", name: "Vanguard Total Stock Market ETF", symbol: "VTI", enabled: true },
  { id: "QQQ", category: "etf", name: "Invesco QQQ Trust", symbol: "QQQ", enabled: true },
  { id: "VEA", category: "etf", name: "Vanguard FTSE Developed Markets ETF", symbol: "VEA" },
  { id: "VTV", category: "etf", name: "Vanguard Value ETF", symbol: "VTV" },
  { id: "BND", category: "etf", name: "Vanguard Total Bond Market ETF", symbol: "BND" },
  { id: "IEFA", category: "etf", name: "iShares Core MSCI EAFE ETF", symbol: "IEFA" },
  { id: "AGG", category: "etf", name: "iShares Core U.S. Aggregate Bond ETF", symbol: "AGG" },
  { id: "VWO", category: "etf", name: "Vanguard FTSE Emerging Markets ETF", symbol: "VWO" },
  { id: "IEMG", category: "etf", name: "iShares Core MSCI Emerging Markets ETF", symbol: "IEMG" },
  { id: "VIG", category: "etf", name: "Vanguard Dividend Appreciation ETF", symbol: "VIG" },
  { id: "IWF", category: "etf", name: "iShares Russell 1000 Growth ETF", symbol: "IWF" },
  { id: "VUG", category: "etf", name: "Vanguard Growth ETF", symbol: "VUG" },
  { id: "IJH", category: "etf", name: "iShares Core S&P Mid-Cap ETF", symbol: "IJH" },
  { id: "GLD", category: "etf", name: "SPDR Gold Shares", symbol: "GLD" },
  { id: "IWM", category: "etf", name: "iShares Russell 2000 ETF", symbol: "IWM" },
  { id: "VNQ", category: "etf", name: "Vanguard Real Estate ETF", symbol: "VNQ" },
  { id: "IJR", category: "etf", name: "iShares Core S&P Small-Cap ETF", symbol: "IJR" },
  { id: "VXUS", category: "etf", name: "Vanguard Total International Stock ETF", symbol: "VXUS" },
  { id: "SCHD", category: "etf", name: "Schwab U.S. Dividend Equity ETF", symbol: "SCHD" },
  { id: "EFA", category: "etf", name: "iShares MSCI EAFE ETF", symbol: "EFA" },
  { id: "IWD", category: "etf", name: "iShares Russell 1000 Value ETF", symbol: "IWD" },
  { id: "BNDX", category: "etf", name: "Vanguard Total International Bond ETF", symbol: "BNDX" },
  { id: "VCIT", category: "etf", name: "Vanguard Intermediate-Term Corporate Bond ETF", symbol: "VCIT" },
  { id: "VO", category: "etf", name: "Vanguard Mid-Cap ETF", symbol: "VO" },
  { id: "XLF", category: "etf", name: "Financial Select Sector SPDR Fund", symbol: "XLF" },
  { id: "XLK", category: "etf", name: "Technology Select Sector SPDR Fund", symbol: "XLK" },
  { id: "ITOT", category: "etf", name: "iShares Core S&P Total U.S. Stock Market ETF", symbol: "ITOT" },
  { id: "VCSH", category: "etf", name: "Vanguard Short-Term Corporate Bond ETF", symbol: "VCSH" },
  { id: "VGT", category: "etf", name: "Vanguard Information Technology ETF", symbol: "VGT" },
  { id: "LQD", category: "etf", name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", symbol: "LQD" },
  { id: "IVW", category: "etf", name: "iShares S&P 500 Growth ETF", symbol: "IVW" },
  { id: "VB", category: "etf", name: "Vanguard Small-Cap ETF", symbol: "VB" },
  { id: "XLE", category: "etf", name: "Energy Select Sector SPDR Fund", symbol: "XLE" },
  { id: "XLV", category: "etf", name: "Health Care Select Sector SPDR Fund", symbol: "XLV" },
  { id: "BSV", category: "etf", name: "Vanguard Short-Term Bond ETF", symbol: "BSV" },
  { id: "VYM", category: "etf", name: "Vanguard High Dividend Yield ETF", symbol: "VYM" },
  { id: "TIP", category: "etf", name: "iShares TIPS Bond ETF", symbol: "TIP" },
  { id: "SCHX", category: "etf", name: "Schwab U.S. Large-Cap ETF", symbol: "SCHX" },
  { id: "IGSB", category: "etf", name: "iShares 1-5 Year Investment Grade Corporate Bond ETF", symbol: "IGSB" },
  { id: "GOVT", category: "etf", name: "iShares U.S. Treasury Bond ETF", symbol: "GOVT" },
  { id: "IWB", category: "etf", name: "iShares Russell 1000 ETF", symbol: "IWB" },
  { id: "MUB", category: "etf", name: "iShares National Muni Bond ETF", symbol: "MUB" },
  { id: "DIA", category: "etf", name: "SPDR Dow Jones Industrial Average ETF Trust", symbol: "DIA" },
  { id: "XLI", category: "etf", name: "Industrial Select Sector SPDR Fund", symbol: "XLI" },
  { id: "SCHB", category: "etf", name: "Schwab U.S. Broad Market ETF", symbol: "SCHB" },
  { id: "VEU", category: "etf", name: "Vanguard FTSE All-World ex-US ETF", symbol: "VEU" },
  { id: "IWR", category: "etf", name: "iShares Russell Mid-Cap ETF", symbol: "IWR" },
  { id: "SPDW", category: "etf", name: "SPDR Portfolio Developed World ex-US ETF", symbol: "SPDW" },
  { id: "DVY", category: "etf", name: "iShares Select Dividend ETF", symbol: "DVY" },
  { id: "IEF", category: "etf", name: "iShares 7-10 Year Treasury Bond ETF", symbol: "IEF" },
  { id: "VTIP", category: "etf", name: "Vanguard Short-Term Inflation-Protected Securities ETF", symbol: "VTIP" },
  { id: "RSP", category: "etf", name: "Invesco S&P 500 Equal Weight ETF", symbol: "RSP" },
  { id: "SHV", category: "etf", name: "iShares Short Treasury Bond ETF", symbol: "SHV" },
  { id: "JPST", category: "etf", name: "JPMorgan Ultra-Short Income ETF", symbol: "JPST" },
  { id: "XLY", category: "etf", name: "Consumer Discretionary Select Sector SPDR Fund", symbol: "XLY" },
  { id: "XLP", category: "etf", name: "Consumer Staples Select Sector SPDR Fund", symbol: "XLP" },
  { id: "SCHA", category: "etf", name: "Schwab U.S. Small-Cap ETF", symbol: "SCHA" },
  { id: "XLU", category: "etf", name: "Utilities Select Sector SPDR Fund", symbol: "XLU" },
  { id: "SPYV", category: "etf", name: "SPDR Portfolio S&P 500 Value ETF", symbol: "SPYV" },
  { id: "SDY", category: "etf", name: "SPDR S&P Dividend ETF", symbol: "SDY" },
  { id: "MINT", category: "etf", name: "PIMCO Enhanced Short Maturity Active ETF", symbol: "MINT" },
  { id: "IWS", category: "etf", name: "iShares Russell Mid-Cap Value ETF", symbol: "IWS" },
  { id: "DFAC", category: "etf", name: "Dimensional U.S. Core Equity 2 ETF", symbol: "DFAC" },
  { id: "VTEB", category: "etf", name: "Vanguard Tax-Exempt Bond ETF", symbol: "VTEB" },
  { id: "VBR", category: "etf", name: "Vanguard Small-Cap Value ETF", symbol: "VBR" },
  { id: "VGK", category: "etf", name: "Vanguard FTSE Europe ETF", symbol: "VGK" },
  { id: "SPYG", category: "etf", name: "SPDR Portfolio S&P 500 Growth ETF", symbol: "SPYG" },
  { id: "QUAL", category: "etf", name: "iShares MSCI USA Quality Factor ETF", symbol: "QUAL" },
  { id: "MDY", category: "etf", name: "SPDR S&P Midcap 400 ETF Trust", symbol: "MDY" },
  { id: "SCHF", category: "etf", name: "Schwab International Equity ETF", symbol: "SCHF" },
  { id: "EEM", category: "etf", name: "iShares MSCI Emerging Markets ETF", symbol: "EEM" },
  { id: "SPTS", category: "etf", name: "SPDR Portfolio Short Term Treasury ETF", symbol: "SPTS" },
  { id: "IWP", category: "etf", name: "iShares Russell Mid-Cap Growth ETF", symbol: "IWP" },
  { id: "ESGU", category: "etf", name: "iShares ESG Aware MSCI USA ETF", symbol: "ESGU" },
  { id: "DGRO", category: "etf", name: "iShares Core Dividend Growth ETF", symbol: "DGRO" },
  { id: "DFAS", category: "etf", name: "Dimensional U.S. Small Cap ETF", symbol: "DFAS" },
  { id: "IWN", category: "etf", name: "iShares Russell 2000 Value ETF", symbol: "IWN" },
  { id: "SPLG", category: "etf", name: "SPDR Portfolio S&P 500 ETF", symbol: "SPLG" },
  { id: "VBK", category: "etf", name: "Vanguard Small-Cap Growth ETF", symbol: "VBK" },
  { id: "ACWI", category: "etf", name: "iShares MSCI ACWI ETF", symbol: "ACWI" },
  { id: "USMV", category: "etf", name: "iShares MSCI USA Min Vol Factor ETF", symbol: "USMV" },
  { id: "FTCS", category: "etf", name: "First Trust Capital Strength ETF", symbol: "FTCS" },
  { id: "SPAB", category: "etf", name: "SPDR Portfolio Aggregate Bond ETF", symbol: "SPAB" },
  { id: "DFUS", category: "etf", name: "Dimensional U.S. Equity ETF", symbol: "DFUS" },
  { id: "JEPI", category: "etf", name: "JPMorgan Equity Premium Income ETF", symbol: "JEPI" },
  { id: "HYG", category: "etf", name: "iShares iBoxx $ High Yield Corporate Bond ETF", symbol: "HYG" },
  { id: "SHY", category: "etf", name: "iShares 1-3 Year Treasury Bond ETF", symbol: "SHY" },
  { id: "EMB", category: "etf", name: "iShares J.P. Morgan USD Emerging Markets Bond ETF", symbol: "EMB" },
  { id: "IUSB", category: "etf", name: "iShares Core Total USD Bond Market ETF", symbol: "IUSB" },
  { id: "SCHG", category: "etf", name: "Schwab U.S. Large-Cap Growth ETF", symbol: "SCHG" },
  { id: "IEI", category: "etf", name: "iShares 3-7 Year Treasury Bond ETF", symbol: "IEI" },
  { id: "VLUE", category: "etf", name: "iShares MSCI USA Value Factor ETF", symbol: "VLUE" },
  { id: "FLOT", category: "etf", name: "iShares Floating Rate Bond ETF", symbol: "FLOT" },
  { id: "VGSH", category: "etf", name: "Vanguard Short-Term Treasury ETF", symbol: "VGSH" },
  { id: "JPMB", category: "etf", name: "JPMorgan USD Emerging Markets Sovereign Bond ETF", symbol: "JPMB" },
  { id: "VMBS", category: "etf", name: "Vanguard Mortgage-Backed Securities ETF", symbol: "VMBS" },
  { id: "DFIV", category: "etf", name: "Dimensional International Value ETF", symbol: "DFIV" },
];
